#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_SWIVEL_ENABLED
#define AP_SWIVEL_ENABLED 1
#endif

#ifndef AP_SWIVEL_BACKEND_DEFAULT_ENABLED
#define AP_SWIVEL_BACKEND_DEFAULT_ENABLED AP_SWIVEL_ENABLED
#endif

#ifndef AP_SWIVEL_PIN_ENABLED
#define AP_SWIVEL_PIN_ENABLED AP_SWIVEL_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AP_SWIVEL_DRONECAN_ENABLED
#define AP_SWIVEL_DRONECAN_ENABLED AP_SWIVEL_BACKEND_DEFAULT_ENABLED && HAL_ENABLE_DRONECAN_DRIVERS
#endif